config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'welcome/home', to: 'welcome#home'
  get 'welcome/about', to: 'welcome#about'
  
  resources :articles
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'about', to: 'page#about'
  get 'page/homepage', to: 'page#homepage'
  root 'page#homepage'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	validates :title, presence: true, length: { minimum:3, maximum:50}
	validates :description, presence: true, length: { minimum:10, maximum:300}
	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :articles, dependent: :destroy
	before_save { self.email = email.downcase }
	
	validates :username, presence: true,
	uniqueness: { case_sensitive: false },
	length: { minimum: 3, maximum: 25 }
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	
	validates :email, presence: true, length: { maximum: 105 },
	uniqueness: { case_sensitive: false },
	format: { with: VALID_EMAIL_REGEX }
	
	has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?
  
  
  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
  	!!current_user
  end

  #TODO check ruby style guide concerning the negative if statement
  def require_user
  	if !logged_in?
  		flash[:danger] = "You must be logged in"
  		redirect_to root_path
  	end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :show, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @articles = Article.paginate(page: params[:page], per_page: 4)

  end

  def new
    @article = Article.new
  end

  def edit

  end

  def create
    #render plain: params[:article].inspect

    @article = Article.new(article_params)


    if @article.save
      flash[:success] = "article was successfully created"
      redirect_to article_path(@article)

    else

      render :new
    end
  end

  def update


    if @article.update(article_params)
      flash[:success] = "Article was updated"
      redirect_to edit_article_path(@article)
    else
      render :edit
    end
  end

  def show

  end

  def destroy

    @article.destroy

    redirect_to articles_path
    flash[:danger] = "Article deleted"
  end

  private
  def set_article
    @article = Article.find(params[:id])
  end


  def article_params
    params.require(:article).permit(:title, :description, :user_id)
  end

  def require_same_user
    if current_user != @article.user and !current_user.admin?
      flash[:danger] = "you can only edit your own articles"
      redirect_to root_path
    end

  end

end

app/controllers/page_controller.rb
class PageController < ApplicationController

  def homepage
  	redirect_to articles_path if logged_in?
  end
  
  
  def about
  
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new 
	
	end

	def create 
		user = User.find_by(email: params[:session][:email])
		
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "logged in #{user.username}"
			redirect_to user_path(user)
		
		else
			flash.now[:danger] = "Incorrect login details"
			render 'new'
		end
		
	end
	
	def destroy 
		session[:user_id] = nil
		flash[:success] = "logged out"
		redirect_to root_path
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  before_action :require_admin, only: [:destroy]

	def index 
		@users = User.paginate(page: params[:page], per_page: 4)
	end
	
	def new 
		@user = User.new
	end
	
	def create
		@user = User.new(user_params)
		
		if @user.save 
			flash[:success] = "welcome to our blog #{@user.username}"
			redirect_to articles_path
		else
			render 'new'
		end
		
	end
	
	def edit
		
		
	end
	
	def show
	
		@user_articles = @user.articles.paginate(page: params[:page], per_page: 2)
		
	end

  def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:danger] = "user and all articles have been deleted"
		redirect_to users_path
	end
	

	
	def update 
	
		if @user.update(user_params)
			flash[:success] = "your account was updated"
			redirect_to user_path(@user)
		else
		
		render 'edit'
		
		end
		
	end
	
	private 
		def user_params
			params.require(:user).permit(:username, :email, :password)
		end
		
	def set_user
			@user = User.find(params[:id])
	end

  def require_same_user
		if current_user != @user and !current_user.admin?
			flash[:danger] = "you can only edit your own account"
			redirect_to root_path
		end
	end

  def require_admin
		if logged_in? and !current_user.admin?
			flash[:danger] = "only admin users can do this"
			redirect_to root_path
		end
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def home
  	
  end
  
  
  def about
  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
	<div class="row">
		<div class="col-xs-8 col-xs-offset-2">
			<div class="well well-lg">
				<div class="article-title">
					<%= link_to article.title, article_path(article) %>
				</div>
				<div class="article-body">
					<%= truncate(article.description, lenght: 100) %>
					<div class="article-meta-details">
					<small>Created by: <%= article.user.username if article.user %>,
													  	<%= time_ago_in_words(article.created_at) %> ago,
													  	<%= time_ago_in_words(article.updated_at) %> ago,
					</small>
					</div>
				</div>
				
				<% if logged_in? && (current_user == article.user || current_user.admin?) %>
				<div class="article-actions">
					<%= link_to "edit", edit_article_path(article), class: "btn btn-xs btn-primary" %>
					<%= link_to "Delete", article_path(article), method: :delete, 
																									data: { confirm: "Are you shure"}, 
																									class: "btn btn-xs btn-danger" %>
																									
				</div>
				<% end %>
				
			</div>
		</div>
	</div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>

<div class="row">
	<div class="col-xs-8 col-xs-offset-3">
		<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= f.label :title %>
			</div>
			<div class="col-sm-6">	
				<%= f.text_field :title, class: "form-control", placeholder: "Title", autofocus:true %>
			</div>
		</div>
		<div class="form-group">
			<div class="control-label col-sm-2">
			
				<%= f.label :description %>
			</div>
			
			<div class="col-sm-6">	
				<%= f.text_area :description, rows: 10, class: "form-control", placeholder: "description" %>
			</div>
			
			<div class="col-sm-6">	
				 <%= f.collection_select :user_id, User.all, :id, :username, prompt: true %>
			</div>
			
			
		</div>
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<%= f.submit class: "btn btn-primary btn-lg" %>
			</div>
		</div>
				
		
		
		<% end %>
		
		<p>
			<%= link_to "back to articles listing", articles_path %>
		</p>
		
	</div>
</div>

app/views/articles/edit.html.erb
<h1>Article edit page</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Articles lijst</h1>
<div align="center">
	<%= will_paginate %>
</div>
<%=   %>
<%= render 'article', obj: @articles %>	
<div align="center">
	<%= will_paginate %>
</div>

app/views/articles/new.html.erb
<div class="">
<h1 align="center">Create an article</h1>
</div>
<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center"><%= @article.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-lg">
        <div class="article-title">
          <%= link_to @article.user.username, user_path(@article.user) if @article.user %>
        </div>
        <div class="article-body">
          <%= truncate(@article.user.email, lenght: 100) if @article.user %>
          <div class="article-meta-details">


          </div>
        </div>

      </div>
    </div>
  </div>


  <h4 class="center"><strong>Description:<strong></h4>
  <hr>
  <%= simple_format(@article.description) %>

  <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
      <div class="article-actions">
        <%= link_to "edit", edit_article_path(@article), class: "btn btn-xs btn-primary" %>


        <%= link_to "Delete", article_path(@article), method: :delete,
                    data: {confirm: "Are you shure"},
                    class: "btn btn-xs btn-danger" %>

  <% end %>


  <%= link_to "View all", articles_path, class: "btn btn-xs btn-success" %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>Copyright &copy; 2016 </small>
	</footer>
	
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
		</ul>	
	</nav>
	
</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
	<% flash.each do |name, msg| %>
		<div class='alert alert-<%= "#{name}" %>'>
		<a href="#" class="close" data-dismiss="alert">&#215;</a>
		<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)%>
		</div>
<% end %>

</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Test App", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Users", users_path %></li>

        <% if logged_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Article
                Functions <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "New Article", new_article_path %></li>
                <li role="separator" class="divider"></li>
                <li><a href="#menu-toggle" class="btn btn-default" id="menu-toggle">Toggle Menu</a></li>

              </ul>
            </li>


            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">User
                Functions <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "New User", signup_path %></li>
                <li role="separator" class="divider"></li>


              </ul>
            </li>
        <% end %>

      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
            <li><%= "Administrator" if current_user.admin? %></li>
            <li><%= link_to("Logout", logout_path, method: :delete) if session[:user_id] %></li>


            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">You
                profile <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Edit profile", edit_user_path(current_user) %></li>
                <li><%= link_to "View profile", user_path(current_user) %></li>
              </ul>
            </li>
        <% else %>
            <li><%= link_to("Login", login_path) %></li>
            <li><%= link_to("Signup", signup_path) %></li>
        <% end %>


      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_sidemenu.html.erb
<div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Start Bootstrap
                    </a>
                </li>
                <li>
                    <a href="#">Dashboard</a>
                </li>
                <li>
                    <a href="#">Shortcuts</a>
                </li>
                <li>
                    <a href="#">Overview</a>
                </li>
                <li>
                    <a href="#">Events</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/sidemenu' %>
  	<%= render 'layouts/navigation' %>
  	<%= render 'layouts/messages' %>
  	<div class="container">
    	<%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    
     <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>
  </body>
</html>

app/views/page/about.html.erb
<!DOCTYPE html>
<html>
<head>
<style>
div.container {
    width: 100%;
    border: 1px solid gray;
}

header, footer {
    padding: 1em;
    color: white;
    background-color: black;
    clear: left;
    text-align: center;
}

nav {
    float: left;
    max-width: 160px;
    margin: 0;
    padding: 1em;
}

nav ul {
    list-style-type: none;
    padding: 0;
}
   
nav ul a {
    text-decoration: none;
}

article {
    margin-left: 170px;
    border-left: 1px solid gray;
    padding: 1em;
    overflow: hidden;
}
</style>
</head>
<body>

<div class="container">

<header>
   <h1>	<%= link_to 'Home', page_homepage_path %></h1>
   
    <%= image_tag 'ka.png' %>
</header>
  
<nav>
  <ul>
    <li><a href="#">London</a></li>
    <li><a href="#">Paris</a></li>
    <li><a href="#">Tokyo</a></li>
  </ul>
</nav>

<article>


  <p>London is the capital city of England. It is the most populous city in the  United Kingdom, with a metropolitan area of over 13 million inhabitants.</p>
  <p>Standing on the River Thames, London has been a major settlement for two millennia, its history going back to its founding by the Romans, who named it Londinium.</p>
</article>

<footer></footer>

</div>

</body>
</html>

app/views/page/homepage.html.erb
<div class="center jumbotron">
  <h1>Test APP</h1>
   <%= link_to 'Sign up now', "#", class: "btn btn-primary btn-lg btn-xlarge" %>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>

<div class="row">
	<div class="col-xs-8">
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h2 class="panel-title">
				<%= pluralize(obj.errors.count, "error") %>
				prohibited the article to save:
				</h2>
				<div class="panel-body">
					<ul>
						<% obj.errors.full_messages.each do |msg| %>
							<li><%= msg %></li>
						<% end %>
					</ul>
					<% end %>
					</div>
				</div>
			</div>
		</div>

app/views/users/edit.html.erb
<h1>Edit your account</h1>

<%= render 'shared/errors', obj: @user %>

<div class="row">
  <div class="col-xs-8 col-xs-offset-3">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :username %>
          </div>
          <div class="col-sm-6">
            <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">

            <%= f.label :email %>
          </div>

          <div class="col-sm-6">
            <%= f.email_field :email, class: "form-control", placeholder: "enter email" %>
          </div>
        </div>

        <div class="form-group">
          <div class="control-label col-sm-2">

            <%= f.label :password %>
          </div>

          <div class="col-sm-6">
            <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit "Save", class: "btn btn-primary btn-lg" %>
          </div>
        </div>


    <% end %>

    <p>
      <%= link_to "back to articles listing", articles_path %>
    </p>

  </div>
</div>

app/views/users/index.html.erb
<h1 align="center">Users list</h1>
<div align="center">
  <%= will_paginate %>
</div>
<% @users.each do |user| %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="well well-lg">
          <div class="article-title">
            <%= link_to user.username, user_path(user) %>
          </div>
          <div class="article-body">
            <%= truncate(user.email, lenght: 100) %>
            <div class="article-meta-details">
              <small>
                <%= time_ago_in_words(user.created_at) %> ago,
                <%= time_ago_in_words(user.updated_at) %> ago,
                Heeft <%= user.articles.count() %> articles
                <% if logged_in? and current_user.admin? %>
                    <li>
                <%= link_to "delete user", users_path(user), method: :delete,
                           data: {confirm: "are you shure, this will delte their articles aswell"} %>
                  <li>
                   <% end %>
                   </small>
					
					
					</div>
                   </div>
				
				<div class="article-actions">
					<%= link_to "edit", edit_user_path(user), class: "btn btn-xs btn-primary" %>
                <%= link_to "Delete", user_path(user), method: :delete,
                            data: {confirm: "Are you shure"},
                            class: "btn btn-xs btn-danger" %>
            </div>
          </div>
        </div>
      </div>
<% end %>
	

app/views/users/new.html.erb
<h1 align="left">Signup</h1>

<%= render 'shared/errors', obj: @user %>

<div class="row">
  <div class="col-xs-8 col-xs-offset-3">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
        <div class="form-group">
          <div class="control-label col-sm-2">
            <%= f.label :username %>
          </div>
          <div class="col-sm-6">
            <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
          </div>
        </div>
        <div class="form-group">
          <div class="control-label col-sm-2">

            <%= f.label :email %>
          </div>

          <div class="col-sm-6">
            <%= f.email_field :email, class: "form-control", placeholder: "enter email" %>
          </div>
        </div>

        <div class="form-group">
          <div class="control-label col-sm-2">

            <%= f.label :password %>
          </div>

          <div class="col-sm-6">
            <%= f.password_field :password, class: "form-control", placeholder: "enterpassword_fieldd" %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-2 col-sm-10">
            <%= f.submit "Signup", class: "btn btn-primary btn-lg" %>
          </div>
        </div>


    <% end %>

    <p>
      <%= link_to "back to articles listing", articles_path %>
    </p>

  </div>
</div>

app/views/users/show.html.erb
<h2 align="center"><%= @user.username %></h2>

<div class=" col-xs-8 col-xs-offset-2">
  <h4 class="center"><strong>User:<strong></h4>
  <hr>
  <%= simple_format(@user.username) %>
  <%= simple_format(@user.email) %>
  <div class="article-actions">
    <%= link_to "edit", edit_user_path(@user), class: "btn btn-xs btn-primary" %>
    <%= link_to "View all", users_path, class: "btn btn-xs btn-success" %>
    <%= link_to "Delete", user_path(@user), method: :delete,
                data: {confirm: "Are you shure"},
                class: "btn btn-xs btn-danger" %>
  </div>
  related articles
</div>
<hr>

<%= render 'articles/article', obj: @user_articles %>
<div class="center">
  <%= will_paginate @user_articles %>
</div>

app/views/welcome/about.html.erb
<h1>Hoi about</h1>

<%= link_to 'Home', welcome_home_path %>

app/views/welcome/home.html.erb
<h1>Hoi home</h1>

<%= link_to 'About', welcome_about_path %>